services:
  backend:
    image: hmthu30/ccs-backend:latest
    container_name: rust-backend
    restart: unless-stopped
    # Port 8080 is open to the world here. 
    # If you only want Nginx to talk to it, you can remove "8080:8080"
    ports:
      - "8080:8080"
    volumes:
      - ./data/db:/app/data/db
      - ./data/images:/app/data/images
    environment:
      - DATABASE_URL=sqlite:/app/data/db/database.db
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - RUST_LOG=info
    networks:
      - ccs-network

  frontend:
    image: hmthu30/ccs-frontend:latest
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      # This looks for nginx.conf in your server's current folder
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - ccs-network

networks:
  ccs-network:
    driver: bridge